name = "Fabulously Optimized"
author = "robotkoer"
version = "13.1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e97b1822400845796a027551be1d47841ac9f0347366f73cc597b8cbee47550e"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
