name = "Fabulously Optimized"
author = "robotkoer"
version = "4.10.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25c6337e10651340ac7468af29017bbaa59784ba8da8abc3ce1bda26d95b2a3d"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
