name = "Fabulously Optimized"
author = "robotkoer"
version = "14.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "507e85347b7c232503c9a1fe0d6dc628bc3bbaa82b0fa941e3a1f3c4849b4b4f"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
