name = "Fabulously Optimized"
author = "robotkoer"
version = "14.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7d3c92589988b61cfad8e4343338cd4a2307a84585b2ed3304c8a75c67c6d31"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
