name = "Fabulously Optimized"
author = "robotkoer"
version = "15.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "655a6234ca1d16bc5d57174e75b56c531f1ac608a943710fc273e1991396dcf8"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
