name = "Fabulously Optimized"
author = "robotkoer"
version = "5.4.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1aa20be67bea31f77362a06972a7815373090195f86556b9c2e2b234ab4be79"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
