name = "Fabulously Optimized"
author = "robotkoer"
version = "5.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97de49eb4dc02eb455b29522e5e6ee8c5cb021a9922f9ee279ba46807c7f9bd0"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
