name = "Fabulously Optimized"
author = "robotkoer"
version = "5.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05a54a66b8aa5ae1d634a4309e5a205bbab37597ec61c107e3755dd54a40b418"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"
