name = "Fabulously Optimized"
author = "robotkoer"
version = "9.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ea13ceda317a9686712570085fff7dde735b01b856543a03051201fffdacca2"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
