name = "Fabulously Optimized"
author = "robotkoer"
version = "9.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "182a1bc9843237a15e21348e037d258ab6c40c3b1315262623c7e7f85b07268f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
