name = "Fabulously Optimized"
author = "robotkoer"
version = "13.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c4e6b9358216cc91670a8b6bd58e496b57bb5d889cf28ef2018483dad2bd58"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
