name = "Fabulously Optimized"
author = "robotkoer"
version = "13.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ede8dec90470157fb694b9daca672de07ac636892ef905d68be9792d4cf4dfd9"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
