name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.2-pw.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07f04714d3d0943e351f135c07fc6ae4626068ea38435029c270ca7a9ca85175"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
