name = "Fabulously Optimized"
author = "robotkoer"
version = "4.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "019727be2817b3eb83f3db0fbeec3da2095095c78916b2d9615e9ee8a938de6f"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
