name = "Fabulously Optimized"
author = "robotkoer"
version = "4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adf4c52479b94c3a1982f5038344124008d437ce9fe0f7d54bd1bdc7fd9bdb20"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
