name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.1-pw.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "113f58df71b038c50277b04fc72999b225b45b77b22039a2a412490a735cade9"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
