name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d55a76af401db7616148f07e8a1d49af89db2070eda2ce0f772f1a6757e3ffb5"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
