name = "Fabulously Optimized"
author = "robotkoer"
version = "4.3.2-pw.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32087fc000499f42f34ad206529a7f5b404d1210d1c87375cf4b7a6f330b1296"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
