name = "Fabulously Optimized"
version = "4.2.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "356f1b0785771745c74f69aef794f92b641c649fc58f68700ec73467b67718b6"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
