name = "Fabulously Optimized"
author = "robotkoer"
version = "4.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "261fd25577bc4b1c403cc13099fb091221d95787abcf474b48efefcea9ef736d"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
