name = "Fabulously Optimized"
author = "robotkoer"
version = "4.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88212eae58af40285d302686786aff2407756b94fdc1a497c50a1b0925b533f4"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
