name = "Fabulously Optimized"
author = "robotkoer"
version = "8.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e91dd4dc22af8045513809352fc63ff42543f872612627b2f7086177a4b27a3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.4"
