blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://www.curseforge.com/minecraft/modpacks/fabulously-optimized#reply
    about: General questions and support will be provided on the modpack's Curseforge page
