blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://download.fo/discord
    about: General questions and support will be provided on the modpack's Discord
