name: Mod request
description: Suggest a new mod to be included in Fabulously Optimized
labels: mod
body:
- type: markdown
  attributes:
    value: |
      ## Mod name ⤴️
      Before you request a mod, [please search](https://github.com/Fabulously-Optimized/fabulously-optimized/issues) if it has already been requested.
      With this modpack, less is more. [Consider the principles as well.](https://fabulously-optimized.gitbook.io/modpack/readme/principles)

- type: input
  attributes:
    label: CurseForge link
    description: If it exists, please write it.
    placeholder: https://www.curseforge.com/minecraft/mc-mods/...
  validations:
    required: false
      
- type: dropdown
  attributes:
    label: CurseForge Mod Distribution
    description: If the mod is on CurseForge, please fill it.
    multiple: false
    options:
      - Allowed
      - Not allowed
  validations:
    required: false
    
- type: markdown
  attributes:
    value: |
      1. Go to https://cflookup.com
      2. Paste the mod link to "Project Id / Slug" and click `Search project`
      3. Look at the `Mod Distribution` value and select it above

- type: input
  attributes:
    label: Modrinth link
    description: If it exists, please write it.
    placeholder: https://modrinth.com/mod/...
  validations:
    required: false

- type: input
  attributes:
    label: Source/other link
    description: E.g. GitHub or GitLab, optional.
    placeholder: https://...
  validations:
    required: false

- type: input
  attributes:
    label: Mod file size
    description: This is found on Curseforge, Modrinth and GitHub releases and is used to determine mod size-purpose ratio. Write "unknown" only if there are no public versions yet. 
    placeholder: 123.45 KB
  validations:
    required: true

- type: textarea
  attributes:
    label: What it does
    description: A short description of what the mod does. 
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it be in the modpack
    description: How can the mod benefit everyone while keeping the experience "vanilla-like"?
  validations:
    required: true

- type: textarea
  attributes:
    label: Why shouldn't it be in the modpack
    description: Don't forget to include any downsides of the mod, you know every mod has some.
    placeholder: |
      Examples: not available in CurseForge/Modrinth, still in beta, depends on something, has confusing settings, not very vanilla-like etc.
  validations:
      required: true

- type: dropdown
  attributes:
    label: Categories
    description: Select all that match the mod.
    multiple: true
    options:
      - Performance optimization
      - Graphics optimization
      - New feature
      - Works like OptiFine/Bedrock Edition/Forge/etc
      - Fixes a bug/makes another mod work
      - Replaces an existing mod
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional details
    description: Anything else you want to add?
  validations:
    required: false
