name: Bug report
description: Report an issue with the modpack
labels: bug
body:
- type: markdown
  attributes:
    value: |
      If it is a crash and you know what mod caused it (e.g. it says on the crash report), please report the issue to that mod instead.
      Otherwise you can still report any crashes to me, and we\'ll try to find the problem cause together. 

- type: textarea
  attributes:
    label: Describe the bug
    description: A short summary of the issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: What you expected to see.
  validations:
    required: true

- type: textarea
  attributes:
    label: Observed/actual behavior
    description: What you actually saw.
  validations:
      required: true

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Launched Minecraft
      2. Clicked ...
      3. Clicked ...
      4. ... works incorrectly
  validations:
    required: true

- type: input
  attributes:
    label: Modpack version
    description: What version of the modpack are you using?
  validations:
    required: true

- type: dropdown
  attributes:
    label: Launcher
    description: Which launcher are you using?
    options:
      - Curseforge Launcher
      - MultiMC
      - GDLauncher
      - Minecraft Launcher (vanilla)
      - Other (please write below)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Install method
    description: How did you install the modpack?
    options:
      - Fresh install/new profile
      - Upgraded an existing profile (please write below, what version to what version)
      - Other (please write below)
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: Optionally add screenshots, video or any other information. If it is a crash, please post it to [Pastebin](https://pastebin.com) and add a link here.
    placeholder: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
