name: Bug report
description: Report an issue with the modpack in its unmodified state. For other issues, use Discord.
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Before reporting an issue, [please search](https://github.com/Fabulously-Optimized/fabulously-optimized/issues) to make sure it has not already been reported. 

- type: textarea
  attributes:
    label: Describe the bug
    description: Describe your issue. For bad FPS and crashes you'll get a faster answer [from our Discord.](https://fabulously-optimized.github.io/discord)
  validations:
    required: true

- type: input
  attributes:
    label: Modpack version
    description: What version of the modpack are you using?
    placeholder: Find it in the bottom right corner of the main menu
  validations:
    required: true

- type: dropdown
  attributes:
    label: Launcher
    description: Which launcher are you using?
    options:
      - CurseForge Launcher
      - Prism Launcher
      - MultiMC
      - MultiMC (auto-update)
      - Minecraft Launcher (vanilla)
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Confirm
    options:
      - label: This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.
        required: true
    
- type: textarea
  attributes:
    label: Additional context
    description: Screenshots, video or any other information. If it is a crash, please post it to [mclo.gs](https://mclo.gs/) and add a link here.
    placeholder: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
