name: Setting change
description: Suggest an option/config/keybind/etc change in an existing mod or tool
labels: option
body:
- type: markdown
  attributes:
    value: |
      Before you request a config change, [please search](https://github.com/Madis0/fabulously-optimized/issues) if it has already been requested and see [if it has already been changed](https://fabulously-optimized.gitbook.io/modpack/readme/changed-options). 
      If it has been changed and you don't see it, [make sure you are on the latest version](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions) and [reset your settings](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions#resetting-settings).

- type: textarea
  attributes:
    label: What config to change
    description: Describe the change you want me to make. This is NOT the place to request new features that do not already exist in included mods, ask that from the mods themselves.
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it be changed
    description: How can the change benefit everyone while keeping the experience "vanilla-like"?
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional details
    description: Anything else you want to add?
  validations:
    required: false
