name: Setting change
description: Suggest an option/config/keybind/etc change in an existing mod or tool. Use this also for suggestions about Mod Menu Helper, Chat Reporting Helper or Fast Better Grass.
labels: option
body:
- type: markdown
  attributes:
    value: |
      Before you request a config change, [please search](https://github.com/Madis0/fabulously-optimized/issues) if it has already been requested and see [if it has already been changed](https://wiki.download.fo/changed-options#options). 
      If it has been changed and you don't see it, [make sure you are on the latest version](https://download.fo/update) and [reset your settings](https://wiki.download.fo/update-instructions#resetting-options).

- type: textarea
  attributes:
    label: What config to change
    description: Describe the change you want to suggest in the configuration of the modpack.
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it be changed
    description: How can the change benefit everyone while keeping the experience "vanilla-like"?
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional details
    description: Anything else you want to add?
  validations:
    required: false

- type: input
  attributes:
    label: Discord discussion link
    description: Was this also discussed on the Fabulously Optimized Discord (optional)? If so, copy the link here.
    placeholder: https://discord.com/channels/859124104644788234/...
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Confirm
    options:
      - label: This is a request to change the configuration of the modpack, whether by adjusting vanilla settings, mod settings, instance structure or something else. This is not a request for new features that do not already exist in added mods.
        required: true