name = "Fabulously Optimized"
author = "robotkoer"
version = "6.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb322e4271d6744ee760aea8a7ca8ee186a7059887379ac30469f1f7702dee4a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
