name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b44dce723be0cf14ef7e52f59750e7e26d379ba7981dead5da673240b3bee6bb"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
