name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92ecd2d58b6dfb4df8160150a16b2bc238e503cd22d84ae16324b43ccef547e4"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
