name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-beta.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d95563016a4c6b78e40f2412c6940578d0f381a1d451072ece929f5963f99b6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
