name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a09e9677fc0cfa33d50800f58ba8c6916e6d7da1d70c03f2bd4cc56b935def7"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
