name = "Fabulously Optimized"
author = "robotkoer"
version = "10.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7f708dce6148e1d55e89c175ca7ac1b2c411c5fcc1bb184796ca51d91b4974f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
