name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d93407e89e13b2af8916813f49879afa9192e72729d03fa8bb3b8b0a6307279c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
