name = "Fabulously Optimized"
author = "robotkoer"
version = "12.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3de9e7a7d8a2f7da28b9838a1ffe2e6388a80c6ab9afb5ae4561a12969be71"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
