name = "Fabulously Optimized"
author = "robotkoer"
version = "6.3.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "137a62d3a6b1a7d99a91c951f56e212ab891647cb078167f92001027ea94c17d"

[versions]
fabric = "0.16.7"
minecraft = "1.21.2"
