name = "Fabulously Optimized"
author = "robotkoer"
version = "5.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2f034a23bbc17cf720960c43afaedf20624ea0c6089fb43534ba89e40d4118d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
