name = "Fabulously Optimized"
author = "robotkoer"
version = "5.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08c6faf35582e0ff027c7132e4c8b44bf5d57793b4b5ef3667fb2adaf5b0697c"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
