name = "Fabulously Optimized"
version = "4.0.0-beta.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82338bc6e031a59fdcd43d8fea8a4be5ca2bcef99d0c915e8f6dd210758451e8"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
