name = "Fabulously Optimized"
version = "4.0.0-beta.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13ad38a70c58c9dd981929db374c5af0dd317f64cc943bb2ca3c54589e3f6ef"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
