name = "Fabulously Optimized"
version = "4.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a44d32f7aa0afaef0d578a26f21547e9a78d7523296da05a925bea82005d613"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
