name = "Fabulously Optimized"
version = "3.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec6cdb3fbdbb53a47de1a11b604824c0938497208a7fb619e077b17c06015c30"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
