name = "Fabulously Optimized"
version = "3.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9855c1ba01cf98f024a2e84276b8d303c61d9085f5801b6aadd26b214a8d263b"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
