name = "Fabulously Optimized"
version = "3.8.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "241a39b4fc57b7c2d603fcee290285b704a3cd29d836b23136fa611f4ebe8554"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
