name = "Fabulously Optimized"
author = "robotkoer"
version = "11.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bda6dd1df22416fdb736b8c80c83d581896815143919c63ee9bfad938f9cb6d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
