name = "Fabulously Optimized"
author = "robotkoer"
version = "13.2.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e2609f2256464beaa80503a5f03b2ab9185a6fd805882ca808c2d915260a490"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
