name = "Fabulously Optimized"
author = "robotkoer"
version = "13.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98de9696e3a9dbe4ee85d933c9b48e4d95eb004b7ec4bf08835a7e75f5c1c2e3"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
