name = "Fabulously Optimized"
author = "robotkoer"
version = "13.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e02447240518a43cbcdf0f3f363a350550a65bf115a4a023764abe679e7cae1"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
