name = "Fabulously Optimized"
author = "robotkoer"
version = "4.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4a4ae9686d40bc30378ccaeac7d4daa8dde79ddb6035a21ed45c6041dae1acb"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
