name = "Fabulously Optimized"
author = "robotkoer"
version = "4.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3d71a2f52baf0397e1559c0353eb63fee29ddebb5db5c7abc12772272a36143"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
