name = "Fabulously Optimized"
author = "robotkoer"
version = "4.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "575e8f0fcf35b7c6ab2341d4a4eff944278c099340f0ced794cf335128f4f31c"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
