name = "Fabulously Optimized"
author = "robotkoer"
version = "4.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2233b45fe38ecba53fefb98290dfa19ee207d34f3d7f7f6e3aa05f9882112b69"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
