name = "Fabulously Optimized"
author = "robotkoer"
version = "4.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a41cc71316721832fa48240fff79472eb2f4167d33067a1753daa18c46c2bfa"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
