name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dde5e3a694bb670da8a1a2802a909e0ee35252074d8eb799e9f7384fd37737ca"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
