name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e23d9871e3a7b55e1a7d37cfb8a19193f23887cade77af09b9cc001f88610629"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
